// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Scrim struct {
	ID               uuid.UUID             `json:"id"`
	UserID           uuid.UUID             `json:"user_id"`
	Title            string                `json:"title"`
	Description      sql.NullString        `json:"description"`
	Videodescription pqtype.NullRawMessage `json:"videodescription"`
	VideoUrl         sql.NullString        `json:"video_url"`
	OplogUrl         sql.NullString        `json:"oplog_url"`
	Duration         sql.NullInt32         `json:"duration"`
	Published        sql.NullBool          `json:"published"`
	CreatedAt        sql.NullTime          `json:"created_at"`
	UpdatedAt        sql.NullTime          `json:"updated_at"`
}

type User struct {
	Userid      uuid.UUID             `json:"userid"`
	Username    string                `json:"username"`
	Email       string                `json:"email"`
	Password    string                `json:"password"`
	Enabled     bool                  `json:"enabled"`
	Description pqtype.NullRawMessage `json:"description"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}
