// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrimfiles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createScrimFiles = `-- name: CreateScrimFiles :one
INSERT INTO scrimfiles (scrim_id, filename, language, location, content, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, scrim_id, filename, language, location, content, description, created_at, updated_at
`

type CreateScrimFilesParams struct {
	ScrimID     uuid.UUID             `json:"scrim_id"`
	Filename    string                `json:"filename"`
	Language    string                `json:"language"`
	Location    string                `json:"location"`
	Content     string                `json:"content"`
	Description pqtype.NullRawMessage `json:"description"`
}

func (q *Queries) CreateScrimFiles(ctx context.Context, arg CreateScrimFilesParams) (Scrimfile, error) {
	row := q.db.QueryRowContext(ctx, createScrimFiles,
		arg.ScrimID,
		arg.Filename,
		arg.Language,
		arg.Location,
		arg.Content,
		arg.Description,
	)
	var i Scrimfile
	err := row.Scan(
		&i.ID,
		&i.ScrimID,
		&i.Filename,
		&i.Language,
		&i.Location,
		&i.Content,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScrimFileById = `-- name: GetScrimFileById :one
SELECT id, scrim_id, filename, language, location, content, description, created_at, updated_at FROM scrimfiles WHERE id = $1
`

func (q *Queries) GetScrimFileById(ctx context.Context, id uuid.UUID) (Scrimfile, error) {
	row := q.db.QueryRowContext(ctx, getScrimFileById, id)
	var i Scrimfile
	err := row.Scan(
		&i.ID,
		&i.ScrimID,
		&i.Filename,
		&i.Language,
		&i.Location,
		&i.Content,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScrimFilesByScrimId = `-- name: GetScrimFilesByScrimId :many
SELECT id, scrim_id, filename, language, location, content, description, created_at, updated_at FROM scrimfiles WHERE scrim_id = $1
`

func (q *Queries) GetScrimFilesByScrimId(ctx context.Context, scrimID uuid.UUID) ([]Scrimfile, error) {
	rows, err := q.db.QueryContext(ctx, getScrimFilesByScrimId, scrimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scrimfile
	for rows.Next() {
		var i Scrimfile
		if err := rows.Scan(
			&i.ID,
			&i.ScrimID,
			&i.Filename,
			&i.Language,
			&i.Location,
			&i.Content,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
