// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrims.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createScrim = `-- name: CreateScrim :one
INSERT INTO scrims (user_id, title, description, video_url, oplog_url, duration, videodescription)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, description, videodescription, video_url, oplog_url, duration, published, created_at, updated_at, mode, files
`

type CreateScrimParams struct {
	UserID           uuid.UUID             `json:"user_id"`
	Title            string                `json:"title"`
	Description      sql.NullString        `json:"description"`
	VideoUrl         sql.NullString        `json:"video_url"`
	OplogUrl         sql.NullString        `json:"oplog_url"`
	Duration         sql.NullInt32         `json:"duration"`
	Videodescription pqtype.NullRawMessage `json:"videodescription"`
}

func (q *Queries) CreateScrim(ctx context.Context, arg CreateScrimParams) (Scrim, error) {
	row := q.db.QueryRowContext(ctx, createScrim,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.VideoUrl,
		arg.OplogUrl,
		arg.Duration,
		arg.Videodescription,
	)
	var i Scrim
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Videodescription,
		&i.VideoUrl,
		&i.OplogUrl,
		&i.Duration,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Files,
	)
	return i, err
}

const getScrimByID = `-- name: GetScrimByID :one
SELECT id, user_id, title, description, videodescription, video_url, oplog_url, duration, published, created_at, updated_at, mode, files FROM scrims WHERE id = $1
`

func (q *Queries) GetScrimByID(ctx context.Context, id uuid.UUID) (Scrim, error) {
	row := q.db.QueryRowContext(ctx, getScrimByID, id)
	var i Scrim
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Videodescription,
		&i.VideoUrl,
		&i.OplogUrl,
		&i.Duration,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Files,
	)
	return i, err
}

const getScrimByUser = `-- name: GetScrimByUser :many
SELECT id, user_id, title, description, videodescription, video_url, oplog_url, duration, published, created_at, updated_at, mode, files FROM scrims WHERE user_id = $1
`

func (q *Queries) GetScrimByUser(ctx context.Context, userID uuid.UUID) ([]Scrim, error) {
	rows, err := q.db.QueryContext(ctx, getScrimByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scrim
	for rows.Next() {
		var i Scrim
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Videodescription,
			&i.VideoUrl,
			&i.OplogUrl,
			&i.Duration,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mode,
			&i.Files,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScrims = `-- name: ListScrims :many
SELECT id, user_id, title, description, videodescription, video_url, oplog_url, duration, published, created_at, updated_at, mode, files FROM scrims WHERE published = true
`

func (q *Queries) ListScrims(ctx context.Context) ([]Scrim, error) {
	rows, err := q.db.QueryContext(ctx, listScrims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scrim
	for rows.Next() {
		var i Scrim
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Videodescription,
			&i.VideoUrl,
			&i.OplogUrl,
			&i.Duration,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mode,
			&i.Files,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScrimAssets = `-- name: UpdateScrimAssets :exec
UPDATE scrims
SET video_url = $2,
    oplog_url = $3,
    duration = $4,
    published = $5
WHERE id = $1
`

type UpdateScrimAssetsParams struct {
	ID        uuid.UUID      `json:"id"`
	VideoUrl  sql.NullString `json:"video_url"`
	OplogUrl  sql.NullString `json:"oplog_url"`
	Duration  sql.NullInt32  `json:"duration"`
	Published sql.NullBool   `json:"published"`
}

func (q *Queries) UpdateScrimAssets(ctx context.Context, arg UpdateScrimAssetsParams) error {
	_, err := q.db.ExecContext(ctx, updateScrimAssets,
		arg.ID,
		arg.VideoUrl,
		arg.OplogUrl,
		arg.Duration,
		arg.Published,
	)
	return err
}
